### ISSUE TITLE
Bad response for Not Found resources

### ISSUE THREAD

**Issue by peillis** [mschae/trailing_format_plug#15] opened 2017-01-23 15:42 UTC
Having this plug if I ask for a url like http://localhost:4000/hey.txt I receive a response with a 404 status (which is good, because I have no such file), but "Internal server error" as body.

Investigating I've seen that a template 404.txt has been assigned (view_template: "404.txt") and I guess then the following code in ErrorView is executed:

```elixir
  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
```

giving the bad body message.

**Comment by mschae** [comment] 2017-01-24 19:15
I think this is a dupe of #10 - I will reopen that one and check it out. Currently travelling so short on time but should get around to this quickly.

**Closed as completed** 2017-01-24 19:15 UTC
